/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppShell: typeof import('./components/common/AppShell.vue')['default']
    CompleteStep: typeof import('./components/settings/migration/CompleteStep.vue')['default']
    ConfigStep: typeof import('./components/settings/migration/ConfigStep.vue')['default']
    DependencyTreeDialog: typeof import('./components/file/DependencyTreeDialog.vue')['default']
    FileItem: typeof import('./components/file/FileItem.vue')['default']
    FilePreview: typeof import('./components/file/FilePreview.vue')['default']
    IndexStatusBar: typeof import('./components/common/IndexStatusBar.vue')['default']
    MigrationWizard: typeof import('./components/settings/migration/MigrationWizard.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NotificationBell: typeof import('./components/common/NotificationBell.vue')['default']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    PreviewStep: typeof import('./components/settings/migration/PreviewStep.vue')['default']
    ProgressStep: typeof import('./components/settings/migration/ProgressStep.vue')['default']
    RecentUploadsFull: typeof import('./components/file/RecentUploadsFull.vue')['default']
    RecoveryDialog: typeof import('./components/settings/migration/RecoveryDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestStep: typeof import('./components/settings/migration/TestStep.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
    UploadManager: typeof import('./components/upload/UploadManager.vue')['default']
    UserInfoSection: typeof import('./components/user/UserInfoSection.vue')['default']
    UserPasswordSection: typeof import('./components/user/UserPasswordSection.vue')['default']
    UserStorageSection: typeof import('./components/user/UserStorageSection.vue')['default']
  }
}
